name = "Rethinking"
uuid = "e2bb8afa-29e4-4736-9c1c-50902cbe280d"
authors = ["andreas koher"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
